version: 2.1

jobs:
  lint-frontend:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Lint Code
          command: npm run lint

  test-frontend:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Unit Tests
          command: npm run test:unit

  build-frontend:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npm run build