version: 2.1

jobs:
  lint-frontend:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Lint Code
          command: npx vue-cli-service lint

  build-frontend:
    docker:
      - image: node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Project
          command: npx vue-cli-service build

workflows:
  version: 2
  frontend_pipeline:
    jobs:
      - lint-frontend
      - test-frontend:
          requires:
            - lint-frontend
      - build-frontend:
          requires:
            - test-frontend
