apiVersion: v1  # Menentukan versi API Kubernetes yang digunakan untuk membuat Service.
kind: Service  # Menyatakan bahwa objek yang dibuat adalah Service.
metadata:
  name: order-service  # Nama unik untuk Service ini agar dapat dikenali dalam cluster.
spec:
  selector:
    app: order-service  # Service ini akan mengarahkan lalu lintas ke pod yang memiliki label "app: order-service".
  ports:  # Daftar port yang akan diekspos oleh Service ini.
    - protocol: TCP  # Menggunakan protokol TCP untuk komunikasi jaringan.
      port: 3000  # Port yang diekspos oleh Service di dalam cluster.
      targetPort: 3000  # Port pada pod yang menerima lalu lintas dari Service.
  type: ClusterIP  # Jenis Service yang digunakan, dalam hal ini "ClusterIP", yang hanya dapat diakses dari dalam cluster.
