apiVersion: apps/v1  # Menentukan versi API yang digunakan untuk membuat Deployment.
kind: Deployment  # Menyatakan bahwa objek yang dibuat adalah Deployment.
metadata:
  name: order-service  # Memberikan nama unik untuk Deployment ini agar dapat dikenali dalam cluster.
spec:
  replicas: 1  # Menentukan jumlah replika (pod) yang akan dijalankan.
  selector:  # Menentukan pod yang akan dikelola oleh Deployment ini.
    matchLabels:
      app: order-service  # Hanya pod dengan label "app: order-service" yang akan dikelola oleh Deployment ini.
  template:  # Template untuk membuat pod baru berdasarkan spesifikasi yang diberikan.
    metadata:
      labels:
        app: order-service  # Memberikan label pada pod yang dibuat agar cocok dengan selector.
    spec:  
      containers:  # Daftar container yang akan dijalankan dalam pod.
        - name: order-service  # Nama container dalam pod.
          image: ghcr.io/ilmialimudins/order-service:latest  # Gambar container yang digunakan (diambil dari GitHub Container Registry).
          ports:
            - containerPort: 3000  # Menentukan port dalam container yang akan diekspos.
          env:  # Menentukan variabel lingkungan (environment variables) untuk container.
            - name: PORT
              value: "3000"  # Menentukan bahwa aplikasi akan berjalan di port 3000 dalam container.
            - name: AMQP_URL
              value: "amqp://rabbitmq-service:5672"  # URL untuk menghubungkan ke RabbitMQ, sesuaikan dengan service dan port RabbitMQ.
