apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-frontend
  template:
    metadata:
      labels:
        app: karsajobs-frontend
    spec:
      containers:
      - name: vue-frontend
        image: ilmi35/karsajobs-ui:latest
        ports:
        - containerPort: 8000

      - name: prometheus-exporter
        image: nginx/nginx-prometheus-exporter
        args:
        - "-nginx.scrape-uri=http://127.0.0.1:8000/nginx_status"
        ports:
        - containerPort: 9113
